####################################################################
#### viya-services-start.yml                                    ####
####################################################################
#### Author: SAS Institute Inc.                                 ####
####################################################################
#
# Copyright (c) 2019-2021, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
---
- import_playbook: ../common/handle_hostgroup_hyphens.yml
  tags:
    - always

- hosts: sas_all
  become: yes
  become_user: root
  gather_facts: false
  any_errors_fatal: true
  vars_files:
    - viya-services-vars.yml
  tasks:
    - name: Check the accessibility of the hosts
      ping:

    - name: Check disk space for Viya log directory
      script: viya-svs.sh checkspace /opt/sas/viya/config/var/log {{log_diskspace_minimum}}
      changed_when: false
      check_mode: no

- hosts: consul
  become: yes
  become_user: root
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Start SAS Primary Consul Server
      script: viya-svs.sh start sas-viya-consul-default

    - name: Start SAS Secret Manager (Vault)
      script: viya-svs.sh start sas-viya-vault-default

- hosts: sas_all:!consul
  become: yes
  become_user: root
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Start SAS Local Consul Servers
      script: viya-svs.sh start sas-viya-consul-default

- hosts: sas_all
  become: yes
  become_user: root
  gather_facts: false
  any_errors_fatal: true
  vars_files:
    - ../../../vars.yml
  tasks:
    - block:
      - name: Start SAS Infrastructure Data Server Consul Template pgpool
        include_tasks: viya-dbct.yml
        vars:
          dbname: "{{INVOCATION_VARIABLES[inventory_hostname]['pgpoolc'][0]['SERVICE_NAME']|default([])}}"
          dbaction: startdbct
          dbtype: pgpool
        when: INVOCATION_VARIABLES[inventory_hostname]['pgpoolc'] is defined and INVOCATION_VARIABLES[inventory_hostname]['pgpoolc'][0]['HA_PGPOOL_VIRTUAL_IP'] is defined

      - name: Start SAS Infrastructure Data Server Consul Template node
        include_tasks: viya-dbct.yml
        vars:
          dbname: "{{INVOCATION_VARIABLES[inventory_hostname]['sasdatasvrc'][0]['SERVICE_NAME']|default([])}}"
          dbaction: startdbct
          dbtype: node
        when: INVOCATION_VARIABLES[inventory_hostname]['sasdatasvrc'] is defined

      - name: Start SAS Infrastructure Data Server Consul Template pgpool
        include_tasks: viya-dbct.yml
        vars:
          dbname: "{{INVOCATION_VARIABLES[inventory_hostname]['cpspgpoolc'][0]['SERVICE_NAME']|default([])}}"
          dbaction: startdbct
          dbtype: pgpool
        when: INVOCATION_VARIABLES[inventory_hostname]['cpspgpoolc'] is defined and INVOCATION_VARIABLES[inventory_hostname]['cpspgpoolc'][0]['HA_PGPOOL_VIRTUAL_IP'] is defined

      - name: Start SAS Infrastructure Data Server Consul Template node
        include_tasks: viya-dbct.yml
        vars:
          dbname: "{{INVOCATION_VARIABLES[inventory_hostname]['cpsdatasvrc'][0]['SERVICE_NAME']|default([])}}"
          dbaction: startdbct
          dbtype: node
        when: INVOCATION_VARIABLES[inventory_hostname]['cpsdatasvrc'] is defined

      - name: Start SAS Infrastructure Data Server
        include_tasks: "{{item}}"
        loop:
          - viya-db.yml
          - viya-dbcheck.yml
        vars:
          dbname: "{{INVOCATION_VARIABLES[inventory_hostname]['pgpoolc'][0]['SERVICE_NAME']|default([])}}"
          dbaction: startdb
          dbnum:  "{{INVOCATION_VARIABLES[inventory_hostname]['pgpoolc'][0]['POOL_NUMBER']|default([])}}"
          dbtype: pgpool
        when: INVOCATION_VARIABLES[inventory_hostname]['pgpoolc'] is defined

      - name: Start SAS Infrastructure Data Server
        include_tasks: "{{item}}"
        loop:
          - viya-db.yml
          - viya-dbcheck.yml
        vars:
          dbname: "{{INVOCATION_VARIABLES[inventory_hostname]['cpspgpoolc'][0]['SERVICE_NAME']|default([])}}"
          dbaction: startdb
          dbnum:  "{{INVOCATION_VARIABLES[inventory_hostname]['cpspgpoolc'][0]['POOL_NUMBER']|default([])}}"
          dbtype: pgpool
        when: INVOCATION_VARIABLES[inventory_hostname]['cpspgpoolc'] is defined

      when: INVOCATION_VARIABLES[inventory_hostname] is defined

- hosts: rabbitmq
  become: yes
  become_user: root
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Start SAS Message Broker (RabbitMQ)
      script: viya-svs.sh start sas-viya-rabbitmq-server-default

- hosts: httpproxy
  become: yes
  become_user: root
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Start SAS HTTP proxy
      script: viya-svs.sh start sas-viya-httpproxy-default

- hosts: sas_casserver_primary
  become: yes
  become_user: root
  gather_facts: false
  any_errors_fatal: true

  tasks:
    - name: Start SAS CAS servers
      script: viya-svs.sh startcas

- hosts: ComputeServer:sas_casserver_*:programming
  become: yes
  become_user: root
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Start SAS multi-tenant services
      script: viya-svs.sh startmt

- hosts: CoreServices
  become: yes
  become_user: root
  gather_facts: false
  any_errors_fatal: true
  vars_files:
    - viya-services-vars.yml
  tasks:
    - name: Start cachelocator/cacheserver
      script: viya-svs.sh start sas-viya-cachelocator-default sas-viya-cacheserver-default
      when: enable_svs_alternative|bool == true

- hosts: elasticsearch
  become: yes
  become_user: root
  gather_facts: false
  any_errors_fatal: true
  vars_files:
    - viya-services-vars.yml
  tasks:
    - name: Start Elasticsearch
      script: viya-svs.sh start sas-viya-svi-elasticsearch-default
      
- hosts: sas_all
  become: yes
  become_user: root
  gather_facts: false
  any_errors_fatal: true
  vars_files:
    - viya-services-vars.yml
  tasks:
    - name: Start SAS all services using alternative script which might take a while
      script: viya-svs-alternative.sh 1 start
      when: enable_svs_alternative|bool == true

- hosts: consul,rabbitmq,httpproxy,pgpoolc,sasdatasvrc,sas_casserver_primary,elasticsearch
  become: yes
  become_user: root
  gather_facts: false
  any_errors_fatal: true
  vars_files:
    - viya-services-vars.yml
  tasks:
    - block:

      - name: Check SAS svas command existence
        stat:
          path: /etc/init.d/sas-viya-all-services
        register: svas_rc

      - name: Start SAS all services which might take a while
        shell: /etc/init.d/sas-viya-all-services start
        register: svas1
        when: svas_rc.stat.exists == true

      when: enable_svs_alternative|bool != true

- hosts: sas_all:!consul:!rabbitmq:!httpproxy:!pgpoolc:!sasdatasvrc:!sas_casserver_primary
  become: yes
  become_user: root
  gather_facts: false
  any_errors_fatal: true
  vars_files:
    - viya-services-vars.yml
  tasks:
    - block:

      - name: Check SAS svas command existence
        stat:
          path: /etc/init.d/sas-viya-all-services
        register: svas_rc

      - name: Start SAS all services which might take a while
        shell: /etc/init.d/sas-viya-all-services start
        register: svas2
        when: svas_rc.stat.exists == true

      when: enable_svs_alternative|bool != true

- hosts: sas_all
  become: yes
  become_user: root
  gather_facts: false
  any_errors_fatal: true
  vars_files:
    - viya-services-vars.yml
  tasks:
    - block:

      - name: Rerun start SAS services if needed
        shell: /etc/init.d/sas-viya-all-services start
        when: not ansible_check_mode and ((svas1 is defined and (svas1.stdout is search('Failed!') or svas1.stdout is search('timeout'))) or (svas2 is defined and (svas2.stdout is search('Failed!') or svas2.stdout is search('timeout'))))
        register: svasall
        until: svasall.stdout.find('Failed!') == -1 and svasall.stdout.find('timeout') == -1
        retries: "{{svas_retry_count}}"
        delay: "{{svas_delay_timer}}"

      when: enable_svs_alternative|bool != true

- hosts: rabbitmq
  become: yes
  become_user: root
  gather_facts: false
  any_errors_fatal: true
  vars_files:
    - viya-services-vars.yml
  tasks:
    
      - name: Start service zookeeper 
        ansible.builtin.service:
          name: zookeeper
          state: started
    
      - name: Start service zookeeper 
        ansible.builtin.service:
          name: zookeeper
          state: started
          
- hosts: BusinessOrchestration
  become: yes
  become_user: root
  gather_facts: false
  any_errors_fatal: true
  vars_files:
    - viya-services-vars.yml
  tasks:
    
      - name: Start service REDIS
        ansible.builtin.service:
          name: redis
          state: started
    
      - name: Start service BOSS and SASRTSNG 
        ansible.builtin.service:
          name: boss
          state: started
